name: ✨ Feature Request
description: Suggest an improvement or enhancement for the portfolio
title: "[Feature] "
labels: [enhancement]
assignees:
  - Saur-Hub
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for contributing to the portfolio!
        Fill in the details below to propose a new enhancement or feature.

  - type: input
    id: feature_title
    attributes:
      label: Feature Title
      placeholder: "Add dark/light mode toggle"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the purpose and expected user experience of this feature.
      placeholder: "I'd like to add a toggle button to switch between dark and light themes."
    validations:
      required: true

  - type: checkboxes
    id: affected_files
    attributes:
      label: Which files need to be updated?
      options:
        - label: index.html
        - label: likes.html
        - label: now-playing.html
        - label: css/style.css
        - label: js/matrix.js
        - label: README.md

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
      default: 1
